//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHere
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public long ID { get; set; }
        public Nullable<long> USERID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> PHONE { get; set; }
        public string SHIPPING_ADDRESS { get; set; }
        public Nullable<int> PINCODE { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
    
        public virtual USER_RECORD USER_RECORD { get; set; }
    }
}
